var base = 10;
var height = 5;
var triangleArea = (base * height) / 2;
console.log("Area of Triangle:", triangleArea);
var celsius = 25;
var fahrenheit = (celsius * 9 / 5) + 32;
console.log("Celsius to Fahrenheit:", fahrenheit);
var f = 77;
var c = (f - 32) * 5 / 9;
console.log("Fahrenheit to Celsius:", c);
var a = 3;
var b = 2;
var c1 = 4;
var formula1 = a * a + b * b + c1 * c1 + 2 * a * b + 2 * a * c1 + 2 * b * c1;
console.log("(a + b + c)² =", formula1);
var lenth = 8;
var width = 6;
var rectangleArea = lenth * width;
console.log("Area of Rectangle:", rectangleArea);
var radius = 7;
var circleArea = 3.14 * radius * radius;
console.log("Area of Circle:", circleArea);
var feet = 5;
var inches = feet * 12;
console.log("Feet to Inches:", inches);
var a = 3;
var b = 2;
var formula2 = (a - b) * (a + b);
console.log("a² - b² =", formula2);
var formula3 = a * a - 2 * a * b + b * b;
console.log("(a - b)² =", formula3);
var formula4 = a * a + b * b + c1 * c1 - 2 * a * b - 2 * a * c1 + 2 * b * c1;
console.log("(a - b - c)² =", formula4);
var formula5 = a * a * a - 3 * a * a * b + 3 * a * b * b - b * b * b;
console.log("(a - b)³ =", formula5);
